# Generated by Django 6.0.1 on 2026-01-27 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50,
                 unique=True, verbose_name='Código/Lote')),
                ('categoria', models.CharField(choices=[('detergente', 'Detergentes'), ('suavizante', 'Suavizantes'), (
                    'limpieza', 'Limpieza General'), ('otros', 'Otros')], default='detergente', max_length=20)),
                ('stock_actual', models.DecimalField(
                    decimal_places=2, default=0.0, max_digits=10)),
                ('capacidad_maxima', models.DecimalField(decimal_places=2, default=100.0,
                 help_text='Capacidad total del contenedor (para calcular %)', max_digits=10)),
                ('unidad_medida', models.CharField(
                    default='Lts', max_length=10, verbose_name='Unidad')),
                ('precio', models.DecimalField(
                    decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prenda',
                'verbose_name_plural': 'Prendas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('autoservicio', 'Autoservicio'), ('por_encargo', 'Por encargo'), (
                    'a_domicilio', 'A domicilio'), ('tintoreria', 'Tintoreria')], default='autoservicio', max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['tipo', 'nombre'],
            },
        )
    ]
