# Generated by Django 6.0.1 on 2026-01-27 19:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_notificacionstock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto del Problema')),
                ('descripcion', models.TextField(verbose_name='Descripción Detallada')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('resuelto', 'Resuelto')], default='pendiente', max_length=20)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='incidencias/', verbose_name='Evidencia')),
                ('fecha_reporte', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-fecha_reporte'],
            },
        ),
    ]
