# Generated by Django - Merge migration to resolve conflicting migrations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_pedido_detallepedido_movimientooperador'),
        ('gestion', '0006_incidencia'),
    ]

    operations = [
    ]
