# Generated by Django 6.0.1 on 2026-01-28 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_maquina'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='hora_inicio_uso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='pedido_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquina_asignada', to='gestion.pedido'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='tiempo_asignado',
            field=models.IntegerField(default=0, help_text='Tiempo en minutos'),
        ),
    ]
