# Generated by Django 6.0.1 on 2026-01-30 23:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_gastooperativo_movimientoinsumo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Punto Limpio', max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('horario', models.CharField(default='Lun-Vie: 8:00-20:00, Sáb: 9:00-18:00', max_length=200)),
            ],
            options={
                'verbose_name': 'Configuración del Negocio',
            },
        ),
        migrations.RemoveField(
            model_name='movimientoinsumo',
            name='insumo',
        ),
        migrations.RemoveField(
            model_name='movimientoinsumo',
            name='usuario',
        ),
        migrations.CreateModel(
            name='CorteCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('ventas_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ventas_tarjeta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ventas_transferencia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('efectivo_contado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tarjeta_terminal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transferencia_banco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_fisico', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('justificacion', models.TextField(blank=True, null=True)),
                ('fecha_hora_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cortes_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Corte de Caja',
                'verbose_name_plural': 'Cortes de Caja',
                'ordering': ['-fecha'],
                'unique_together': {('fecha', 'responsable')},
            },
        ),
        migrations.DeleteModel(
            name='GastoOperativo',
        ),
        migrations.DeleteModel(
            name='MovimientoInsumo',
        ),
    ]
