# Generated by Django 6.0.1 on 2026-02-03 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_configuracionnegocio_remove_movimientoinsumo_insumo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoRenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mes', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('anio', models.IntegerField(default=2026)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gasto de Renta',
                'verbose_name_plural': 'Gastos de Renta',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('mes', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='GastoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('agua', 'Agua'), ('luz', 'Luz'), ('gas', 'Gas'), ('internet', 'Internet')], max_length=20)),
                ('monto_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mes', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('anio', models.IntegerField(default=2026)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gasto de Servicio',
                'verbose_name_plural': 'Gastos de Servicios',
                'ordering': ['-anio', '-mes', 'tipo'],
                'unique_together': {('tipo', 'mes', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='SalarioEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_semanal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empleado', models.OneToOneField(limit_choices_to={'rol__in': ['admin', 'operador']}, on_delete=django.db.models.deletion.CASCADE, related_name='salario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salario de Empleado',
                'verbose_name_plural': 'Salarios de Empleados',
                'ordering': ['empleado__rol', 'empleado__username'],
            },
        ),
    ]
