# Generated by Django 6.0.1 on 2026-02-04 00:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_gastorenta_gastoservicio_salarioempleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='tipo_limpieza',
            field=models.CharField(choices=[('detergente', 'Detergente'), ('detergente_delicado', 'Detergente (delicado)'), ('detergente_suave', 'Detergente (suave)'), ('detergente_suavizante', 'Detergente + Suavizante'), ('detergente_voluminosa', 'Detergente (ropa voluminosa)'), ('lavado_seco', 'Otros (lavado en seco)'), ('limpieza_general', 'Limpieza general'), ('limpieza_especializada', 'Otros (limpieza especializada)'), ('detergente_especial', 'Otros (detergente especial / lavado en seco)'), ('detergente_especial_otros', 'Otros (detergente especial)')], default='detergente', help_text='Tipo de limpieza/insumos que requiere esta prenda', max_length=30),
        ),
        migrations.CreateModel(
            name='MovimientoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('consumo_automatico', 'Consumo automatico por pedido'), ('reabastecimiento', 'Reabastecimiento'), ('ajuste_manual', 'Ajuste manual')], default='consumo_automatico', max_length=30)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_nuevo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='gestion.insumo')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_insumos', to='gestion.pedido')),
            ],
            options={
                'verbose_name': 'Movimiento de Insumo',
                'verbose_name_plural': 'Movimientos de Insumos',
                'ordering': ['-fecha'],
            },
        ),
    ]
