# Generated by Django 6.0.2 on 2026-02-05 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_prenda_tipo_limpieza_movimientoinsumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinsumo',
            name='insumo_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimientoinsumo',
            name='insumo_unidad',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movimientoinsumo',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='gestion.insumo'),
        ),
    ]
