# Generated by Django

from django.db import migrations


def crear_prendas_iniciales(apps, schema_editor):
    Prenda = apps.get_model('gestion', 'Prenda')
    
    # Lista de prendas con precios (SEPARADAS INDIVIDUALMENTE)
    prendas_data = [
        # Calcetas
        ('Calcetas', 55),
        
        # Cobertores (SEPARADOS)
        ('Cobertor Individual', 55),
        ('Cobertor Matrimonial', 65),
        ('Cobertor Queen', 75),
        ('Cobertor King', 75),

        # Edredones (SEPARADOS)
        ('Edredon Individual', 65),
        ('Edredon Matrimonial', 75),
        ('Edredon Queen', 85),
        ('Edredon King', 85),

        # Frazadas (SEPARADAS)
        ('Frazada Individual', 40),
        ('Frazada Matrimonial', 50),
        ('Frazada Queen', 50),
        ('Frazada King', 50),

        # Juego de sabanas (SEPARADO)
        ('Juego Sabanas Individual', 50),
        ('Juego Sabanas Matrimonial', 50),
        ('Juego Sabanas Queen', 50),
        ('Juego Sabanas King', 50),
        
        # Cubrecolchon (SEPARADO)
        ('Cubrecolchon Individual', 60),
        ('Cubrecolchon Matrimonial', 60),
        ('Cubrecolchon Queen', 60),
        ('Cubrecolchon King', 60),

        # Otros
        ('Tenis', 60),
        ('Cortinas', 60),
        
        # Peluches (SEPARADOS)
        ('Peluche Chico', 20),
        ('Peluche Mediano', 40),
        ('Peluche Grande', 40),
    ]
    
    for nombre, precio in prendas_data:
        Prenda.objects.get_or_create(
            nombre=nombre,
            defaults={
                'precio': precio,
                'tipo_limpieza': 'detergente',
                'activo': True
            }
        )


def eliminar_prendas(apps, schema_editor):
    Prenda = apps.get_model('gestion', 'Prenda')
    Prenda.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_movimientoinsumo_insumo_nombre_and_more'),
    ]

    operations = [
        migrations.RunPython(crear_prendas_iniciales, eliminar_prendas),
    ]