# Generated by Django 6.0.2 on 2026-02-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Punto Limpio', max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('horario', models.CharField(default='Lun-Vie: 8:00-20:00, Sáb: 9:00-18:00', max_length=200)),
            ],
            options={
                'verbose_name': 'Configuración del Negocio',
            },
        ),
    ]
