from django.urls import path, include
from . import views

urlpatterns = [
    path('inicio/', views.tasks, name='tasks'),
    path('panel-admin/', views.admin_dashboard, name='admin_dashboard'),
    path('panel-trabajador/', views.trabajador_dashboard,
         name='trabajador_dashboard'),
    path('mis-pedidos/', views.cliente_dashboard, name='cliente_dashboard'),
    path('nuevo-servicio/', views.nuevo_servicio, name='nuevo_servicio'),

    path('panel-admin/finanzas/', views.admin_finanzas, name='admin_finanzas'),
    path('panel-admin/usuarios/', views.admin_usuarios, name='admin_usuarios'),
    path('panel-admin/precios/', views.admin_precios, name='admin_precios'),
    path('panel-admin/inventarios/',
         views.admin_inventarios, name='admin_inventarios'),
    path('panel-admin/historial/',
         views.admin_historialVentas, name='admin_historial'),
    path('panel-admin/historial/ventas/',
         views.admin_historialVentas, name='historial_ventas'),
    path('panel-admin/historial/movimientos/',
         views.admin_historialMovimientos, name='historial_movimientos'),
    path('panel-admin/incidencias/',
         views.admin_incidencias, name='admin_incidencias'),
    path('panel-admin/configuracion/',
         views.admin_configuracion, name='admin_configuracion'),
    path('panel-trabajador/', views.trabajador_dashboard,
         name='trabajador_dashboard'),
    path('mis-pedidos/', views.cliente_dashboard, name='cliente_dashboard'),

    path('solicitar-servicio/', views.solicitar_servicio,
         name='solicitar_servicio'),
    path('panel-trabajador/', views.trabajador_dashboard,
         name='trabajador_dashboard'),
    path('mis-pedidos/', views.cliente_dashboard, name='cliente_dashboard'),
    path('nuevo-servicio/', views.nuevo_servicio, name='nuevo_servicio'),
    path('panel-admin/finanzas/', views.admin_finanzas, name='admin_finanzas'),
    path('panel-admin/finanzas/corte-caja/',
         views.admin_corte_caja, name='admin_corte_caja'),
    path('panel-admin/usuarios/', views.admin_usuarios, name='admin_usuarios'),
    path('panel-admin/usuarios/nuevo/',
         views.admin_nuevo_usuario, name='admin_nuevo_usuario'),
    path('panel-admin/usuarios/eliminar/<int:usuario_id>/',
         views.admin_eliminar_usuario, name='admin_eliminar_usuario'),
    path('panel-admin/precios/', views.admin_precios, name='admin_precios'),

    # APIs para gestion de precios
    path('api/actualizar-precio-prenda/', views.actualizar_precio_prenda,
         name='actualizar_precio_prenda'),
    path('api/actualizar-precio-servicio/',
         views.actualizar_precio_servicio, name='actualizar_precio_servicio'),
    path('api/agregar-prenda/', views.agregar_prenda, name='agregar_prenda'),
    path('api/agregar-servicio/', views.agregar_servicio, name='agregar_servicio'),
    path('api/eliminar-prenda/', views.eliminar_prenda, name='eliminar_prenda'),
    path('api/eliminar-servicio/', views.eliminar_servicio,
         name='eliminar_servicio'),
    path('api/precios/', views.obtener_precios_json, name='obtener_precios_json'),
    path('api/buscar-clientes/', views.buscar_clientes, name='buscar_clientes'),

    path('panel-admin/inventarios/',
         views.admin_inventarios, name='admin_inventarios'),
    path('panel-admin/detalles-inventarios/',
         views.admin_detalles_inventario, name='admin_detalles_inventario'),
    path('panel-admin/historial/',
         views.admin_historialVentas, name='admin_historial'),
    path('panel-admin/historial/ventas/',
         views.admin_historialVentas, name='historial_ventas'),
    path('panel-admin/historial/movimientos/',
         views.admin_historialMovimientos, name='historial_movimientos'),
    path('panel-admin/historial/detalle-venta/<int:pedido_id>/',
         views.admin_detalleVenta, name='detalle_venta'),
    path('panel-admin/incidencias/',
         views.admin_incidencias, name='admin_incidencias'),
    path('panel-admin/configuracion/',
         views.admin_configuracion, name='admin_configuracion'),
    path('panel-trabajador/', views.trabajador_dashboard,
         name='trabajador_dashboard'),
    path('mis-pedidos/', views.cliente_dashboard, name='cliente_dashboard'),
    path('solicitar-servicio/', views.solicitar_servicio,
         name='solicitar_servicio'),
    path('perfil/', views.perfil, name='perfil'),
    path('rastrear-servicio/', views.rastrear_servicio, name='rastrear_servicio'),
    path('dudas-quejas/', views.dudas_quejas, name='dudas_quejas'),
    path('autoservicio/', views.autoservicio, name='autoservicio'),
    path('incidencias/', views.incidencias, name='incidencias'),
    path('panel-trabajador/inventario/', views.inventario, name='inventario'),
    path('panel-trabajador/servicios-proceso/',
         views.servicios_proceso, name='servicios_proceso'),
    path('panel-trabajador/detalle-servicio/<int:pedido_id>/',
         views.detalle_servicio, name='detalle_servicio'),
    path('panel-trabajador/estatus-maquina/',
         views.estatus_maquina, name='estatus_maquina'),
    path('seleccionar-servicio/', views.seleccionar_servicio,
         name='seleccionar_servicio'),
    path('terminado/', views.terminado, name='terminado'),
    path('servCosto/', views.servCosto, name='servCosto'),

    # URLs para inventario / vista ADMINISTRADOR
    path('panel-admin/inventarios/editar/<int:id>/',
         views.editar_insumo, name='editar_insumo'),
    path('panel-admin/inventarios/eliminar/<int:id>/',
         views.eliminar_insumo, name='eliminar_insumo'),

    path('api/asignar-maquina/', views.asignar_maquina, name='asignar_maquina'),
    path('ticket/imprimir/<int:pedido_id>/',
         views.imprimir_ticket, name='imprimir_ticket'),

    # --- FLUJO DE ENTREGA Y VALIDACIÓN ---
    path('validar-ticket/', views.validar_ticket, name='validar_ticket'),
    path('api/buscar-pedido/', views.api_buscar_pedido, name='api_buscar_pedido'),
    path('api/entregar-pedido/', views.api_entregar_pedido,
         name='api_entregar_pedido'),

    # --- HISTORIAL ---
    path('panel-trabajador/historial/',
         views.historial_servicios, name='historial_servicios'),
    path('panel-admin/corte-caja/',
         views.admin_corte_caja, name='admin_corte_caja'),
    # Nuevas rutas para finanzas
    path('panel-admin/finanzas/exportar-excel/',
         views.exportar_finanzas_excel, name='exportar_finanzas_excel'),
    path('panel-admin/finanzas/imprimir-reporte/',
         views.imprimir_reporte_finanzas, name='imprimir_reporte_finanzas'),
    path('panel-admin/finanzas/enviar-email/',
         views.enviar_reporte_email, name='enviar_reporte_email'),
    path('panel-admin/finanzas/corte-caja/imprimir/',
         views.imprimir_corte_caja, name='imprimir_corte_caja')


]
