# Generated by Django 6.0.2 on 2026-02-13 21:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorteCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('ventas_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ventas_tarjeta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ventas_transferencia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('efectivo_contado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tarjeta_terminal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transferencia_banco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_fisico', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('justificacion', models.TextField(blank=True, null=True)),
                ('fecha_hora_registro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Corte de Caja',
                'verbose_name_plural': 'Cortes de Caja',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='GastoRenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mes', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('anio', models.IntegerField(default=2026)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gasto de Renta',
                'verbose_name_plural': 'Gastos de Renta',
                'ordering': ['-anio', '-mes'],
            },
        ),
        migrations.CreateModel(
            name='GastoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('agua', 'Agua'), ('luz', 'Luz'), ('gas', 'Gas'), ('internet', 'Internet')], max_length=20)),
                ('monto_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mes', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('anio', models.IntegerField(default=2026)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gasto de Servicio',
                'verbose_name_plural': 'Gastos de Servicios',
                'ordering': ['-anio', '-mes', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='SalarioEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_semanal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salario de Empleado',
                'verbose_name_plural': 'Salarios de Empleados',
                'ordering': ['empleado__rol', 'empleado__username'],
            },
        ),
    ]
