# Generated by Django 6.0.2 on 2026-02-13 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finanzas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cortecaja',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cortes_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='gastorenta',
            unique_together={('mes', 'anio')},
        ),
        migrations.AlterUniqueTogether(
            name='gastoservicio',
            unique_together={('tipo', 'mes', 'anio')},
        ),
        migrations.AddField(
            model_name='salarioempleado',
            name='empleado',
            field=models.OneToOneField(limit_choices_to={'rol__in': ['admin', 'operador']}, on_delete=django.db.models.deletion.CASCADE, related_name='salario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='cortecaja',
            unique_together={('fecha', 'responsable')},
        ),
    ]
