# Generated by Django 6.0.2 on 2026-02-13 21:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código/Lote')),
                ('categoria', models.CharField(choices=[('detergente', 'Detergentes'), ('suavizante', 'Suavizantes'), ('limpieza', 'Limpieza General'), ('otros', 'Otros')], default='detergente', max_length=20)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('capacidad_maxima', models.DecimalField(decimal_places=2, default=100.0, help_text='Capacidad total', max_digits=10)),
                ('unidad_medida', models.CharField(default='Lts', max_length=10, verbose_name='Unidad')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Identificador')),
                ('tipo', models.CharField(choices=[('lavadora', 'Lavadora'), ('secadora', 'Secadora')], default='lavadora', max_length=20)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('mantenimiento', 'Mantenimiento')], default='disponible', max_length=20)),
                ('descripcion_falla', models.TextField(blank=True, null=True)),
                ('hora_inicio_uso', models.DateTimeField(blank=True, null=True)),
                ('tiempo_asignado', models.IntegerField(default=0, help_text='Tiempo en minutos')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insumo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('insumo_unidad', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_movimiento', models.CharField(choices=[('consumo_automatico', 'Consumo automatico por pedido'), ('reabastecimiento', 'Reabastecimiento'), ('ajuste_manual', 'Ajuste manual')], default='consumo_automatico', max_length=30)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_nuevo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Movimiento de Insumo',
                'verbose_name_plural': 'Movimientos de Insumos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('atendida', models.BooleanField(default=False)),
            ],
        ),
    ]
