# Generated by Django 6.0.2 on 2026-02-13 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='pedido_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquina_asignada', to='servicios.pedido'),
        ),
        migrations.AddField(
            model_name='movimientoinsumo',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='inventario.insumo'),
        ),
        migrations.AddField(
            model_name='movimientoinsumo',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_insumos', to='servicios.pedido'),
        ),
        migrations.AddField(
            model_name='notificacionstock',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.insumo'),
        ),
    ]
