# Generated by Django 6.0.1 on 2026-02-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Teléfono'),
        ),
    ]
