# Generated by Django 6.0.2 on 2026-02-13 21:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('peso', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DudaQueja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('resuelto', 'Resuelto')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Duda o Queja',
                'verbose_name_plural': 'Dudas y Quejas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto del Problema')),
                ('descripcion', models.TextField(verbose_name='Descripción Detallada')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('resuelto', 'Resuelto')], default='pendiente', max_length=20)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='incidencias/', verbose_name='Evidencia')),
                ('fecha_reporte', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('respuesta', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-fecha_reporte'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoOperador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('creo_ticket', 'Creo ticket'), ('entrego', 'Entrego'), ('cambio_precio', 'Cambio precio'), ('elimino', 'Elimino'), ('actualizo', 'Actualizo'), ('registro_servicio', 'Registro servicio')], max_length=30)),
                ('detalles', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Movimiento de Operador',
                'verbose_name_plural': 'Movimientos de Operadores',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=20, unique=True)),
                ('tipo_servicio', models.CharField(max_length=50)),
                ('peso', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_prendas', models.IntegerField(default=0)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cobija_tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('lavado_especial', models.BooleanField(default=False)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metodo_pago', models.CharField(default='efectivo', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('listo', 'Listo para entrega'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=20)),
                ('origen', models.CharField(choices=[('cliente', 'Solicitado por cliente'), ('operador', 'Registrado por operador')], default='cliente', max_length=20)),
                ('fecha_recepcion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_recepcion'],
            },
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso_kg', models.DecimalField(decimal_places=3, default=0, help_text='Peso de la prenda en kilogramos', max_digits=6, verbose_name='Peso (KG)')),
                ('tipo_limpieza', models.CharField(choices=[('detergente', 'Detergente'), ('detergente_delicado', 'Detergente (delicado)'), ('detergente_suave', 'Detergente (suave)'), ('detergente_suavizante', 'Detergente + Suavizante'), ('detergente_voluminosa', 'Detergente (ropa voluminosa)'), ('lavado_seco', 'Otros (lavado en seco)'), ('limpieza_general', 'Limpieza general'), ('limpieza_especializada', 'Otros (limpieza especializada)'), ('detergente_especial', 'Otros (detergente especial / lavado en seco)'), ('detergente_especial_otros', 'Otros (detergente especial)')], default='detergente', help_text='Tipo de limpieza/insumos que requiere esta prenda', max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prenda',
                'verbose_name_plural': 'Prendas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('autoservicio', 'Autoservicio'), ('por_encargo', 'Por encargo'), ('a_domicilio', 'A domicilio'), ('tintoreria', 'Tintoreria')], default='autoservicio', max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['tipo', 'nombre'],
            },
        ),
    ]
