# Generated by Django 6.0.2 on 2026-02-13 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dudaqueja',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dudas_quejas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientooperador',
            name='operador',
            field=models.ForeignKey(limit_choices_to={'rol__in': ['operador', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'rol': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='operador',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol__in': ['operador', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientooperador',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='servicios.pedido'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='servicios.pedido'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='prenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.prenda'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.servicio'),
        ),
    ]
