# Generated by Django 6.0.2 on 2026-02-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_datos_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='subtotal_peso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
