# Generated by Django 6.0.2 on 2026-02-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_pedido_subtotal_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='costo_servicio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
